name: Deploy staging - Choose artifact to deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: "IMAGE_TAG"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy artifact
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition my-first-task --query taskDefinition --region us-east-1 > task-definition.json
      - name: Get PR number
        id: pr-num
        run: |
          echo "::set-env name=PR_NUMBER::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: froggy-ecr-repo
          # IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
          # IMAGE_TAG: ${{ steps.pr-num.outputs.PR_NUMBER }}
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: my-first-task
          image: ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.PR_NUMBER}}
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: my-first-service
          cluster: my-cluster
          wait-for-service-stability: true
